"""
End-to-end DIGITAL-TWIN demonstration of motional-state Wigner tomography for a DISPLACED
(coherent) state of fixed amplitude and phase, via the characteristic-function / Ramsey
route (docs/notes/strobo_grating_transfer_function.md, §6-7; engine: grating_tomography).

PIPELINE (run: python -m spike.twin_wigner_tomography):
  1. PREPARE a known coherent state |gamma>, gamma = r e^{i phi} (fixed amplitude+phase).
  2. MEASURE (twin-simulated): the spin-dependent-force / Ramsey characteristic-function
     readout. For each probe displacement beta on a phase-space grid, reading the qubit in
     two bases gives  P_x = 1/2(1 + C Re chi(beta)),  P_y = 1/2(1 + C Im chi(beta)), with
     contrast C; each is sampled with SHOT NOISE (M repetitions -> binomial counts). The
     raw counts are written to docs/examples/wigner_tomography/.
  3. ANALYSE: reconstruct chi_hat(beta) = [(2 n_x/M - 1) + i(2 n_y/M - 1)] / C from the
     counts, then the Wigner function W(alpha) = (1/pi^2) FT[chi_hat] (engine transform).
  4. VALIDATE: compare W to the analytic W of |gamma>; recover the displacement from the
     reconstruction (centroid <alpha> = gamma) -> amplitude and phase.

IMPORTANT (FAIR): the raw data here is SIMULATED by the digital twin, NOT a real
measurement. It is written under docs/examples/ (separate from sources/data/, the real
DAQ path) and every file is labelled twin-simulated. The single-pair Ramsey reach is only
2 eta ~ 0.78, too small to sample chi out to its support; this demo therefore uses the
spin-dependent-force / extended-reach route that scans beta over a controllable region (a
calibrated conditional displacement up to ~N eta), as the note's tomography route requires.

Pure Python + matplotlib (Agg). Reproducible (seeded shot noise).
"""
from __future__ import annotations

import cmath
import math
import random
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

from .engines import grating_tomography as gt  # noqa: E402

_ROOT = Path(__file__).resolve().parent.parent
_DATADIR = _ROOT / "docs" / "examples" / "wigner_tomography"
_FIGDIR = _ROOT / "docs" / "figures"
_RAW = _DATADIR / "coherent_tomography_raw.dat"

# --- the prepared state and the (simulated) measurement settings --------------
GAMMA_R, GAMMA_PHI = 1.3, math.pi / 4.0       # displaced coherent state: amplitude, phase
CONTRAST = 0.90                                # Ramsey fringe contrast (imperfection)
SHOTS = 500                                    # repetitions per (beta, quadrature)
BETA_HALF, BETA_N = 4.0, 25                    # chi-sampling grid: +-4, 25x25 (disk-masked)
ALPHA_HALF, ALPHA_N = 2.5, 51                  # Wigner reconstruction grid
SEED = 20260623
_BLUE, _RED, _GRAY = "#1f77b4", "#d62728", "#888888"


def _binomial_count(p: float, M: int, rng: random.Random) -> int:
    """Shot-noise count out of M (Normal approximation to Binomial(M, p), clamped)."""
    n = round(M * p + math.sqrt(max(M * p * (1.0 - p), 1e-12)) * rng.gauss(0.0, 1.0))
    return min(M, max(0, n))


# --- step 1+2: prepare |gamma>, simulate the SDF/Ramsey chi measurement -------
def simulate(gamma: complex, contrast=CONTRAST, shots=SHOTS,
             beta_half=BETA_HALF, beta_n=BETA_N, seed=SEED):
    """Return raw 'data': list of (beta, n_x, n_y) shot counts on the disk |beta|<=beta_half,
    plus the uniform grid spacing h. chi from the engine; SDF/Ramsey readout + shot noise."""
    rng = random.Random(seed)
    pts, h = gt.square_grid(beta_half, beta_n)
    raw = []
    for b in pts:
        if abs(b) > beta_half:                 # sample a disk, not the square corners
            continue
        chi = gt.chi_coherent(b, gamma)
        px = 0.5 * (1.0 + contrast * chi.real)
        py = 0.5 * (1.0 + contrast * chi.imag)
        raw.append((b, _binomial_count(px, shots, rng), _binomial_count(py, shots, rng)))
    return raw, h


# --- raw data file I/O (self-documenting; twin-simulated provenance) ----------
def write_raw(raw, gamma, h, path=_RAW, contrast=CONTRAST, shots=SHOTS):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write("# Wigner-tomography RAW DATA -- SIMULATED BY THE DIGITAL TWIN (NOT a real "
                "measurement).\n")
        f.write("# Generated by spike/twin_wigner_tomography.py (engine: grating_tomography).\n")
        f.write("# Prepared state: coherent |gamma>, gamma = %.6f %+.6fj "
                "(|gamma|=%.4f, arg=%.4f rad).\n" % (gamma.real, gamma.imag, abs(gamma), cmath.phase(gamma)))
        f.write("# Measurement: SDF/Ramsey characteristic-function readout, two quadratures.\n")
        f.write("#   P_x = 1/2(1 + C Re chi(beta)),  P_y = 1/2(1 + C Im chi(beta));  C=%.3f, "
                "shots M=%d/quadrature.\n" % (contrast, shots))
        f.write("#   beta sampled on the disk |beta|<=%.2f, uniform grid spacing h=%.5f.\n" % (BETA_HALF, h))
        f.write("# columns:  beta_re  beta_im  M  n_x  n_y  P_x  P_y\n")
        for (b, nx, ny) in raw:
            f.write("%+.5f %+.5f %d %d %d %.5f %.5f\n" % (b.real, b.imag, shots, nx, ny, nx / shots, ny / shots))
    return path


def read_raw(path=_RAW):
    """Read back (beta, M, n_x, n_y) rows + the grid spacing h from the header."""
    rows, h = [], None
    with open(path) as f:
        for line in f:
            if line.startswith("#"):
                if "grid spacing h=" in line:
                    h = float(line.split("h=")[1].strip().rstrip("."))
                continue
            p = line.split()
            rows.append((complex(float(p[0]), float(p[1])), int(p[2]), int(p[3]), int(p[4])))
    return rows, h


# --- step 3: reconstruct chi_hat, then the Wigner function --------------------
def reconstruct(rows, contrast, alpha_half=ALPHA_HALF, alpha_n=ALPHA_N, h=None):
    """chi_hat(beta) from the counts, then W(alpha) via the engine's 2-D transform."""
    beta = [r[0] for r in rows]
    chi_hat = [((2.0 * nx / M - 1.0) + 1j * (2.0 * ny / M - 1.0)) / contrast
               for (_b, M, nx, ny) in rows]
    step = 2.0 * alpha_half / (alpha_n - 1)
    ax = [-alpha_half + i * step for i in range(alpha_n)]
    alpha_pts = [complex(x, y) for y in ax for x in ax]
    W = gt.wigner_from_samples(beta, chi_hat, alpha_pts, h * h)
    return chi_hat, beta, W, alpha_pts, ax, step


def recovered_gamma(W, alpha_pts, frac=0.1):
    """Displacement = centroid <alpha> over the W>frac*max region (= gamma for a coherent
    state). Returns the recovered complex amplitude."""
    wmax = max(W)
    num, den = 0j, 0.0
    for w, a in zip(W, alpha_pts):
        if w > frac * wmax:
            num += w * a
            den += w
    return num / den if den else 0j


# --- step 4: figures + report -------------------------------------------------
def make_chi_figure(beta, chi_hat, gamma, out=_FIGDIR / "twin_wigner_chi_data.png"):
    bx = [b.real for b in beta]
    by = [b.imag for b in beta]
    fig, ax = plt.subplots(1, 3, figsize=(13.5, 4.1))
    for a, vals, t in [(ax[0], [c.real for c in chi_hat], "measured Re $\\chi$"),
                       (ax[1], [c.imag for c in chi_hat], "measured Im $\\chi$")]:
        sc = a.scatter(bx, by, c=vals, cmap="RdBu_r", vmin=-1, vmax=1, s=22)
        a.set_aspect("equal"); a.set_title(t + " (M=%d, C=%.2f)" % (SHOTS, CONTRAST))
        a.set_xlabel("Re $\\beta$"); a.set_ylabel("Im $\\beta$")
        fig.colorbar(sc, ax=a, fraction=0.046)
    # 1-D cut along real beta: measured Re chi (+ shot error bars) vs analytic
    cut = sorted([(b.real, c.real) for b, c in zip(beta, chi_hat) if abs(b.imag) < 1e-6])
    xs = [x for x, _ in cut]
    ys = [y for _, y in cut]
    sig = 2.0 * math.sqrt(0.25 / SHOTS) / CONTRAST              # shot error on chi
    ax[2].errorbar(xs, ys, yerr=sig, fmt="o", color=_RED, ms=4, capsize=2, label="measured")
    fine = [(-4 + 8 * i / 300) for i in range(301)]
    ax[2].plot(fine, [gt.chi_coherent(complex(x, 0), gamma).real for x in fine], _BLUE, lw=1.4, label="analytic")
    ax[2].set_xlabel("Re $\\beta$ (cut at Im $\\beta$=0)"); ax[2].set_ylabel("Re $\\chi$")
    ax[2].set_title("data quality (1-D cut)"); ax[2].legend(fontsize=8); ax[2].grid(alpha=0.3)
    fig.suptitle("Step 2-3: measured characteristic function $\\hat\\chi(\\beta)$ "
                 "(twin-simulated, with shot noise)", y=1.02, fontsize=11)
    fig.tight_layout(); out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=140, bbox_inches="tight"); plt.close(fig)
    return out


def make_wigner_figure(W, alpha_pts, ax_lin, gamma, g_rec,
                       out=_FIGDIR / "twin_wigner_reconstruction.png"):
    na = len(ax_lin)
    def grid(vals):
        return [[vals[j * na + i] for i in range(na)] for j in range(na)]
    W_ana = [gt.wigner_coherent(a, gamma) for a in alpha_pts]
    ext = [ax_lin[0], ax_lin[-1], ax_lin[0], ax_lin[-1]]
    vmax = max(W_ana)
    fig, ax = plt.subplots(1, 3, figsize=(14, 4.3))
    for a, dat, t in [(ax[0], grid(W_ana), "analytic $W$ (input $|\\gamma\\rangle$)"),
                      (ax[1], grid(W), "reconstructed $W$ (from raw data)"),
                      (ax[2], grid([r - b for r, b in zip(W, W_ana)]), "residual")]:
        im = a.imshow(dat, origin="lower", extent=ext, cmap="RdBu_r", vmin=-vmax, vmax=vmax)
        a.set_xlabel("Re $\\alpha$"); a.set_ylabel("Im $\\alpha$"); a.set_aspect("equal")
        fig.colorbar(im, ax=a, fraction=0.046)
        a.set_title(t)
    for a in ax[:2]:
        a.plot(gamma.real, gamma.imag, "k+", ms=11, mew=2)
        a.plot(g_rec.real, g_rec.imag, "x", color="lime", ms=9, mew=2)
    fig.suptitle("Step 4: reconstructed Wigner function vs the prepared state  "
                 "(+ = input $\\gamma$, × = recovered)", y=1.02, fontsize=11)
    fig.tight_layout(); out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=140, bbox_inches="tight"); plt.close(fig)
    return out


def report(gamma, g_rec, W, alpha_pts, n_pts):
    W_ana = [gt.wigner_coherent(a, gamma) for a in alpha_pts]
    err = max(abs(r - b) for r, b in zip(W, W_ana))
    L = ["", "Digital-twin Wigner tomography of a displaced coherent state",
         "  Step 1  prepared state : |gamma>, gamma = %.3f e^{i %.3f} = %.3f %+.3fj"
         % (GAMMA_R, GAMMA_PHI, gamma.real, gamma.imag),
         "  Step 2  measured       : SDF/Ramsey chi-readout, %d probe points, C=%.2f, M=%d "
         "shots/quadrature -> raw counts written" % (n_pts, CONTRAST, SHOTS),
         "  Step 3  reconstructed  : chi_hat = (2 n/M - 1)/C ; W = (1/pi^2) FT[chi_hat]",
         "  Step 4  recovered      : <alpha> = %.3f %+.3fj  -> |gamma|=%.3f (input %.3f), "
         "arg=%.3f rad (input %.3f)" % (g_rec.real, g_rec.imag, abs(g_rec), GAMMA_R,
                                        cmath.phase(g_rec), GAMMA_PHI),
         "          max |W_recon - W_analytic| = %.4f  (peak W = %.3f)" % (err, max(W_ana))]
    return "\n".join(L)


def main(argv=None) -> int:
    gamma = GAMMA_R * cmath.exp(1j * GAMMA_PHI)
    raw, h = simulate(gamma)
    write_raw(raw, gamma, h)
    rows, h_read = read_raw()                  # round-trip through the raw file
    chi_hat, beta, W, alpha_pts, ax_lin, _step = reconstruct(rows, CONTRAST, h=h_read)
    g_rec = recovered_gamma(W, alpha_pts)
    print(report(gamma, g_rec, W, alpha_pts, len(rows)))
    f1 = make_chi_figure(beta, chi_hat, gamma)
    f2 = make_wigner_figure(W, alpha_pts, ax_lin, gamma, g_rec)
    print("\nwrote", _RAW.relative_to(_ROOT))
    for f in (f1, f2):
        print("wrote", f.relative_to(_ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
